// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLkd-kYVL8SacEoCIV-0w2DOzrjUWCUHg',
    appId: '1:143622710409:web:6f58beda16bcf246621258',
    messagingSenderId: '143622710409',
    projectId: 'welhome-21',
    authDomain: 'welhome-21.firebaseapp.com',
    storageBucket: 'welhome-21.firebasestorage.app',
    measurementId: 'G-TTQSPSXVNP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuJdXVkGr_JxTC2cWbTNWF5vBmvc_yKEU',
    appId: '1:735015242553:android:f71ab9baab2361eba636e8',
    messagingSenderId: '735015242553',
    projectId: 'welhome-21-27f23',
    storageBucket: 'welhome-21-27f23.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcNWXx2pUqDoC-mmt_gelNYcEjMA3EhC4',
    appId: '1:143622710409:ios:b8c1a0cc26e770d2621258',
    messagingSenderId: '143622710409',
    projectId: 'welhome-21',
    storageBucket: 'welhome-21.firebasestorage.app',
    iosBundleId: 'com.example.welhome',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcNWXx2pUqDoC-mmt_gelNYcEjMA3EhC4',
    appId: '1:143622710409:ios:b8c1a0cc26e770d2621258',
    messagingSenderId: '143622710409',
    projectId: 'welhome-21',
    storageBucket: 'welhome-21.firebasestorage.app',
    iosBundleId: 'com.example.welhome',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLkd-kYVL8SacEoCIV-0w2DOzrjUWCUHg',
    appId: '1:143622710409:web:a5e431a1723ba108621258',
    messagingSenderId: '143622710409',
    projectId: 'welhome-21',
    authDomain: 'welhome-21.firebaseapp.com',
    storageBucket: 'welhome-21.firebasestorage.app',
    measurementId: 'G-9L3CB2CF9B',
  );
}